version: '3'
services:
  nginx:
    image: nginx:1.12
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./log/:/var/log/nginx/
      - ./data/:/usr/share/nginx/html/
    command: [nginx, '-g', 'daemon off;']
